# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install --no-fund --no-audit --no-optional
    - name: Prettier-install
      run: npm install --save-dev prettier-eslint
    - name: serve install
      run: npm install -g serve
    - run: npm run lint
    - run: npm run prettier
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: init serve
      run: serve -s build -l 3000
    - name: E2e test
      uses: cypress-io/github-action@v2
      with: 
        command: npm run test:e2e
        start: nom run start-test
        wait-on: http://localhost:3000
